openapi: 3.0.1
info:
  title: SendToQueueApi
  description: SendToQueueApi
  version: 1.0.0

paths:
  /send:
    post:
      summary: SendToQueue
      description: SendToQueue
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendToQueueApiRequest"
      responses:
        "200":
          description: 200 response
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: NewSqsExercizeFunctionRole.Arn
        uri:
          Fn::Sub:
            - "arn:aws:apigateway:${AWS::Region}:sqs:path/${AWS::AccountId}/${FirstQueue}"
            - FirstQueue: { "Fn::GetAtt" : [ FirstQueue, QueueName ] }
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.header.Content-Type: "'application/x-www-form-urlencoded'"
        requestTemplates:
          application/json: Action=SendMessage&MessageBody=$util.escapeJavaScript($input.body).replaceAll('\\"','"').replaceAll('\\n','')
        passthroughBehavior: never
        httpMethod: POST
        type: aws
components:
  schemas:
    SendToQueueApiRequest:
      type: object
      required:
        - word1
        - word2
      properties:
        word1:
          type: string
        word2:
          type: string