AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LambdaFunctionPersistentCounter

  -funzione Lambda incrementa contatore ad ogni esecuzione
  -endpoint api gateway che esegue una funzione lambda e restituisce il risultato


Globals:
  Function:
    Timeout: 3

Parameters:
  DeployStage:
    Type: String
    Default: "Dev"

Resources:
  ExercizeApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ExercizeApiGateway
      StageName: !Ref DeployStage


  ExercizeFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        IncrementalCounterApiEvent:
          Type: Api 
          Properties:
            RestApiId: !Ref ExercizeApiGateway
            Path: /counter
            Method: get

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  ExercizeApiGateway:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ExercizeApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Staging/counter/"
  ExercizeFunction:
    Description: Exercize function Lambda ARN
    Value: !GetAtt ExercizeFunction.Arn
  ExercizeFunctionIamRole:
    Description: Implicit IAM Role created for ExercizeFunction
    Value: !GetAtt ExercizeFunction.Arn
