AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: 
  E03-Sqs-dql

  Sample SAM Template for E03-Sqs-dql

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SqsExercizeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sqs-elaboration/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FirstQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 1
            Enabled: true

  NewSqsExercizeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-SqsExercizeFunctionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: SqsExercizeFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !GetAtt FirstQueue.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: CLOUDWATCH-LOGS-ARN

  SqsExercizeApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Staging
      DefinitionBody:
        "Fn::Transform":
          Name: AWS::Include
          Parameters:
            Location: ./openapi.yaml

  # SQS Queue
  FirstQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 60
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FirstQueueDlq.Arn
        maxReceiveCount: 3

  # SQS Queue DLQ
  FirstQueueDlq:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 60
      VisibilityTimeout: 30

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SqsExercizeApi:
    Description: "API Gateway endpoint URL for Prod stage for Sqs Exercize function"
    Value: !Sub "https://${SqsExercizeApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Staging/sqs/"
  SqsExercizeFunction:
    Description: "Sqs Exercize Lambda Function ARN"
    Value: !GetAtt SqsExercizeFunction.Arn
  SqsExercizeFunctionIamRole:
    Description: "Implicit IAM Role created for Sqs Exercize function"
    Value: !GetAtt SqsExercizeFunctionRole.Arn
