AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ApigatewayToLambdaToDynamoDB

  Sam Template for an Endpoint to Lambda Function
  that writes something into a DynamoDB's Table
  
Globals:
  Function:
    Timeout: 3

Parameters:
  DeployStage:
    Type: String
    Default: "Dev"
  
Resources:
  E05LambdaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          POWERTOOLS_DEV: true
          DYNAMODB_TABLE: !Ref E05FilmTable 
      Policies: 
        DynamoDBCrudPolicy:
          TableName: !Ref E05FilmTable
      Events:
        DbInsert:
          Type: Api
          Properties:
            Path: /insert
            Method: post   
   
  E05FilmTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: FilmId
          KeyType: HASH
        - AttributeName: Genere
          KeyType: RANGE
      TableName: E05-Film
      AttributeDefinitions:
        - AttributeName: FilmId
          AttributeType: S
        - AttributeName: Genere
          AttributeType: S
Outputs:
  LambdaFunctionArn:
    Description: Lambda Function Arn
    Value: !GetAtt E05LambdaFunction.Arn
              


        
