AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ApigatewayToLambdaToDynamoDB

  Sam Template for an Endpoint to Lambda Function
  that writes something into a DynamoDB's Table
  
Globals:
  Function:
    Timeout: 3

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64

        
